# Generated by Django 2.0.7 on 2018-08-03 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='eatHealthy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatHealthy', to='daily_habits.Habit'),
        ),
        migrations.AddField(
            model_name='day',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='daily_habits.Habit'),
        ),
        migrations.AddField(
            model_name='day',
            name='meditate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditate', to='daily_habits.Habit'),
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
