# Generated by Django 2.0.7 on 2018-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_habits', '0002_auto_20180802_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='completed',
        ),
        migrations.AddField(
            model_name='day',
            name='eatHealthyCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='exerciseCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='meditateCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
