# Generated by Django 2.0.7 on 2018-08-09 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_habits', '0003_auto_20180805_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatHealthy', models.CharField(default='Eat Healthy', max_length=200)),
                ('meditate', models.CharField(default='Meditate', max_length=200)),
                ('exercise', models.CharField(default='Exercise', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='day',
            name='eatHealthy',
        ),
        migrations.RemoveField(
            model_name='day',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='day',
            name='meditate',
        ),
    ]
