# Generated by Django 2.0.7 on 2018-08-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_habits', '0006_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatHealthy', models.CharField(default='Eat Well', max_length=56)),
                ('meditate', models.CharField(default='Meditate', max_length=56)),
                ('exercise', models.CharField(default='Exercise', max_length=56)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
