# Generated by Django 2.0.7 on 2018-08-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_habits', '0009_auto_20180814_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='eatStreak',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='exerciseStreak',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='meditateStreak',
        ),
    ]
