# Generated by Django 2.0.7 on 2018-08-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_habits', '0011_auto_20180818_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='habitOne',
            field=models.CharField(default='Eat Well', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='habitThree',
            field=models.CharField(default='Exercise', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='habitTwo',
            field=models.CharField(default='Meditate', max_length=20),
        ),
    ]
